name: Bump Package.json Version

on:
  push:
    branches:
      - main # Or your main development branch

permissions:
  contents: write # Add this line to grant write permission

jobs:
  bump_version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      

      - name: Get current version
        id: get_version
        run: echo "VERSION=$(jq -r .version package.json)" >> $GITHUB_OUTPUT

      - name: Bump version
        run: |
          NEW_VERSION=$(npm version --new-version $(echo "${{ steps.get_version.outputs.VERSION }}" | sed -E 's/([0-9]+)\.([0-9]+)\.([0-9]+)/\1.\2.$((\3+1))/' --allow-empty))
          echo "New version: $NEW_VERSION"

      - name: Update package.json
        run: |
          sed -i "s/\"version\": \".*\"/\"version\": \"$NEW_VERSION\"/" package.json

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Bump version to ${{ steps.get_version.outputs.VERSION }}"
          push_options: '--force' # Be cautious with --force, consider removing if not needed